### ISSUE TITLE
Invalid SHA1 hash when attempting to open Vita save file

### ISSUE THREAD

**Issue by ChrisHighwind** [gibbed/Gibbed.Borderlands2#17] opened 2017-11-19 19:48 UTC
I'm using the latest release on the GitHub page, and I'm using saves dumped with Vita Save Manager, but I can't seem to load either save as trying to even with the Vita Save File type selected gives me "Invalid SHA1 hash"
Attached is the save file I'm trying to use. I thought Vita Save Manager decrypts saves when you dump them, but I'm not sure now.
[PCSE00383.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/1485908/PCSE00383.zip)

**Comment by Skulledone** [comment] 2017-11-20 19:02
Having the exact same issue with the PS3 game saves.

**Comment by xcier** [comment] 2018-02-22 22:41
decrypt the saves first that is the only issue with SHA1

**Comment by ChrisHighwind** [comment] 2018-02-22 23:53
How exactly do I decrypt a Vita save?

**Comment by PheonixVX** [comment] 2018-06-24 08:02
@ChrisHighwind Use PS3 Game Resigner or Bruteforce

**Comment by gibbed** [comment] 2019-06-14 14:17
Duplicate of #1.

**Closed by gibbed** 2019-06-14 14:17 UTC
